server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    '[bdbe.bdbd]': INFO
    '[org.hibernate.type]': WARN

cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID:}
      secretKey: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME:}
    proxy:
      host: ${AWS_PROXY_HOST:}
      port: ${AWS_PROXY_PORT:0}
    stack:
      auto: false

kakao:
  admin:
    key: ${KAKAOPAY_ADMIN_KEY}
payment:
  external:
    enabled: true
  approval-url: ${PAYMENT_APPROVAL_URL:http://localhost:5173/paymentwaiting}
  cancel-url: ${PAYMENT_CANCEL_URL:http://localhost:5173/paymentfail}
  fail-url: ${PAYMENT_FAIL_URL:http://localhost:5173/paymentfail}
frontend:
  localurl: http://localhost:5173
  prod:
    userurl: ${PROD_USER_FRONTEND_URL:http://localhost:5173}
    ownerurl: ${PROD_OWNER_FRONTEND_URL:http://localhost:5174}

storage:
  s3:
    enabled: ${STORAGE_S3_ENABLED:false}

security:
  jwt:
    secret: ${JWT_SECRET}

# 파일 저장 경로
#file:
#  path: ./images/
