server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    '[bdbe.bdbd]': INFO
    '[org.hibernate.type]': TRACE

cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
    proxy:
      host: krmp-proxy.9rum.cc
      port: 3128
    stack:
      auto: false

kakao:
  admin:
    key: ${KAKAOPAY_ADMIN_KEY}
payment:
  external:
    enabled: true
  approval-url: https://k923062c3c512a.user-app.krampoline.com/paymentwaiting
  cancel-url: https://k923062c3c512a.user-app.krampoline.com/paymentfail
  fail-url: https://k923062c3c512a.user-app.krampoline.com/paymentfail
frontend:
  localurl: http://localhost:5173
  prod:
    userurl: https://k923062c3c512a.user-app.krampoline.com
    ownerurl: https://kae2e326be433a.user-app.krampoline.com

storage:
  s3:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}

# 파일 저장 경로
#file:
#  path: ./images/
